//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapNhom.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAn
    {
        public int MaSoBan { get; set; }
        public string LoaiBan { get; set; }
        public Nullable<int> MaPhieuYeuCau { get; set; }
    
        public virtual PhieuYeuCau PhieuYeuCau { get; set; }
        public virtual PhieuYeuCau PhieuYeuCau1 { get; set; }
    }
}
