//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapNhom.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapThucPham
    {
        public string MaPhieuNhap { get; set; }
        public string MaThucPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual ThucPham ThucPham { get; set; }
    }
}
