//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTapNhom.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucPham()
        {
            this.NhapThucPham = new HashSet<NhapThucPham>();
        }
    
        public string MaThucPham { get; set; }
        public string TenThucPham { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string DVTinh { get; set; }
        public string Nhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapThucPham> NhapThucPham { get; set; }
        public virtual NhomThucPham NhomThucPham { get; set; }

        public void SetData(string MaTP, string TenTP, int DonGia, string DVT)
        {
            MaThucPham = MaTP;
            TenThucPham = TenTP;
            this.DonGia = DonGia;
            this.DVTinh = DVT;
        }
    }
}
